In [2]:
import pandas as pd
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import numpy as np

In [769]:
train=pd.read_csv('~/Desktop/kagel_2/train.csv')
test=pd.read_csv('~/Desktop/kagel_2/test.csv')
sample_submission=pd.read_csv('~/Desktop/kagel_2/sample_submission.csv')

In [770]:
sample_submission # как должен выглядеть ответ

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [771]:
train_cols=list(i for i in train.columns)
print(f'train:{train.shape}')
print(f'test:{test.shape}')

train:(1460, 81)
test:(1459, 80)

In [772]:
for i in train_cols:
    print(train[i].dtype , i)

int64 Id
int64 MSSubClass
object MSZoning
float64 LotFrontage
int64 LotArea
object Street
object Alley
object LotShape
object LandContour
object Utilities
object LotConfig
object LandSlope
object Neighborhood
object Condition1
object Condition2
object BldgType
object HouseStyle
int64 OverallQual
int64 OverallCond
int64 YearBuilt
int64 YearRemodAdd
object RoofStyle
object RoofMatl
object Exterior1st
object Exterior2nd
object MasVnrType
float64 MasVnrArea
object ExterQual
object ExterCond
object Foundation
object BsmtQual
object BsmtCond
object BsmtExposure
object BsmtFinType1
int64 BsmtFinSF1
object BsmtFinType2
int64 BsmtFinSF2
int64 BsmtUnfSF
int64 TotalBsmtSF
object Heating
object HeatingQC
object CentralAir
object Electrical
int64 1stFlrSF
int64 2ndFlrSF
int64 LowQualFinSF
int64 GrLivArea
int64 BsmtFullBath
int64 BsmtHalfBath
int64 FullBath
int64 HalfBath
int64 BedroomAbvGr
int64 KitchenAbvGr
object KitchenQual
int64 TotRmsAbvGrd
object Functional
int64 Fireplaces
object FireplaceQu
object GarageType
float64 GarageYrBlt
object GarageFinish
int64 GarageCars
int64 GarageArea
object GarageQual
object GarageCond
object PavedDrive
int64 WoodDeckSF
int64 OpenPorchSF
int64 EnclosedPorch
int64 3SsnPorch
int64 ScreenPorch
int64 PoolArea
object PoolQC
object Fence
object MiscFeature
int64 MiscVal
int64 MoSold
int64 YrSold
object SaleType
object SaleCondition
int64 SalePrice

In [773]:
# na = train.isna().sum()/len(train)
# na[na>.30]

In [774]:
obj = list(train.select_dtypes(include='object').columns)

In [775]:
intt = list(train.select_dtypes(include='int').columns)

In [776]:
for i in intt:
    train[i] = train[i].fillna(0)
    train[i] = train[i].astype(float)

In [777]:
for i in obj:
    train[i] = train[i].fillna('nan')
    train[i] = train[i].astype(str)

In [778]:
for i in train.columns:
    print(train[i].dtype)

float64
float64
object
float64
float64
object
object
object
object
object
object
object
object
object
object
object
object
float64
float64
float64
float64
object
object
object
object
object
float64
object
object
object
object
object
object
object
float64
object
float64
float64
float64
object
object
object
object
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
object
float64
object
float64
object
object
float64
object
float64
float64
object
object
object
float64
float64
float64
float64
float64
float64
object
object
object
float64
float64
float64
object
object
float64

In [779]:
train['Alley'].astype(str)

0       nan
1       nan
2       nan
3       nan
4       nan
       ...
1455    nan
1456    nan
1457    nan
1458    nan
1459    nan
Name: Alley, Length: 1460, dtype: object

In [780]:
train['Alley'].value_counts()

nan     1369
Grvl      50
Pave      41
Name: Alley, dtype: int64

In [781]:
train=train[train_cols[1:]]

In [782]:
train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60.0,RL,65.0,8450.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,nan,nan,nan,0.0,2.0,2008.0,WD,Normal,208500.0
1,20.0,RL,80.0,9600.0,Pave,nan,Reg,Lvl,AllPub,FR2,...,0.0,nan,nan,nan,0.0,5.0,2007.0,WD,Normal,181500.0
2,60.0,RL,68.0,11250.0,Pave,nan,IR1,Lvl,AllPub,Inside,...,0.0,nan,nan,nan,0.0,9.0,2008.0,WD,Normal,223500.0
3,70.0,RL,60.0,9550.0,Pave,nan,IR1,Lvl,AllPub,Corner,...,0.0,nan,nan,nan,0.0,2.0,2006.0,WD,Abnorml,140000.0
4,60.0,RL,84.0,14260.0,Pave,nan,IR1,Lvl,AllPub,FR2,...,0.0,nan,nan,nan,0.0,12.0,2008.0,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60.0,RL,62.0,7917.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,nan,nan,nan,0.0,8.0,2007.0,WD,Normal,175000.0
1456,20.0,RL,85.0,13175.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,nan,MnPrv,nan,0.0,2.0,2010.0,WD,Normal,210000.0
1457,70.0,RL,66.0,9042.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,nan,GdPrv,Shed,2500.0,5.0,2010.0,WD,Normal,266500.0
1458,20.0,RL,68.0,9717.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,nan,nan,nan,0.0,4.0,2010.0,WD,Normal,142125.0
1459,20.0,RL,75.0,9937.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,nan,nan,nan,0.0,6.0,2008.0,WD,Normal,147500.0

In [783]:
for i in train.columns:
    print(train[i].dtype)

float64
object
float64
float64
object
object
object
object
object
object
object
object
object
object
object
object
float64
float64
float64
float64
object
object
object
object
object
float64
object
object
object
object
object
object
object
float64
object
float64
float64
float64
object
object
object
object
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
object
float64
object
float64
object
object
float64
object
float64
float64
object
object
object
float64
float64
float64
float64
float64
float64
object
object
object
float64
float64
float64
object
object
float64

In [784]:
X=train[train_cols[1:-1]]

In [785]:
y=train[train_cols[-1]]

In [786]:
y

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [787]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2)

In [788]:
X_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1354,60.0,RL,NaN,10316.0,Pave,nan,IR1,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,6.0,2008.0,WD,Normal
153,20.0,RL,NaN,13500.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,3.0,2008.0,WD,Normal
780,20.0,RL,63.0,7875.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,6.0,2007.0,WD,Normal
613,20.0,RL,70.0,8402.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,12.0,2007.0,New,Partial
767,50.0,RL,75.0,12508.0,Pave,nan,IR1,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,Shed,1300.0,7.0,2008.0,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,20.0,RL,NaN,15611.0,Pave,nan,IR1,Lvl,AllPub,Corner,...,0.0,0.0,nan,nan,nan,0.0,3.0,2008.0,WD,Abnorml
146,30.0,RM,51.0,6120.0,Pave,nan,Reg,Lvl,AllPub,Corner,...,0.0,0.0,nan,nan,nan,0.0,11.0,2009.0,WD,Normal
1296,20.0,RL,80.0,8700.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,MnPrv,nan,0.0,12.0,2008.0,WD,Normal
189,120.0,RL,41.0,4923.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,224.0,0.0,nan,nan,nan,0.0,8.0,2008.0,WD,Normal
1147,70.0,RL,75.0,12000.0,Pave,nan,Reg,Bnk,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,7.0,2009.0,WD,Normal

In [789]:
X=X_train
y=y_train

In [790]:
X

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1354,60.0,RL,NaN,10316.0,Pave,nan,IR1,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,6.0,2008.0,WD,Normal
153,20.0,RL,NaN,13500.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,3.0,2008.0,WD,Normal
780,20.0,RL,63.0,7875.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,6.0,2007.0,WD,Normal
613,20.0,RL,70.0,8402.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,12.0,2007.0,New,Partial
767,50.0,RL,75.0,12508.0,Pave,nan,IR1,Lvl,AllPub,Inside,...,0.0,0.0,nan,nan,Shed,1300.0,7.0,2008.0,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,20.0,RL,NaN,15611.0,Pave,nan,IR1,Lvl,AllPub,Corner,...,0.0,0.0,nan,nan,nan,0.0,3.0,2008.0,WD,Abnorml
146,30.0,RM,51.0,6120.0,Pave,nan,Reg,Lvl,AllPub,Corner,...,0.0,0.0,nan,nan,nan,0.0,11.0,2009.0,WD,Normal
1296,20.0,RL,80.0,8700.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,0.0,0.0,nan,MnPrv,nan,0.0,12.0,2008.0,WD,Normal
189,120.0,RL,41.0,4923.0,Pave,nan,Reg,Lvl,AllPub,Inside,...,224.0,0.0,nan,nan,nan,0.0,8.0,2008.0,WD,Normal
1147,70.0,RL,75.0,12000.0,Pave,nan,Reg,Bnk,AllPub,Inside,...,0.0,0.0,nan,nan,nan,0.0,7.0,2009.0,WD,Normal

In [791]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

for i in obj:
    X[i]= label_encoder.fit_transform(X[i])

In [792]:
model = XGBRegressor()

In [793]:
model

XGBRegressor(base_score=None, booster=None, colsample_bylevel=None,
             colsample_bynode=None, colsample_bytree=None, gamma=None,
             gpu_id=None, importance_type='gain', interaction_constraints=None,
             learning_rate=None, max_delta_step=None, max_depth=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             random_state=None, reg_alpha=None, reg_lambda=None,
             scale_pos_weight=None, subsample=None, tree_method=None,
             validate_parameters=None, verbosity=None)

In [794]:
model.fit(X_train,y_train)
# model.score(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=4, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [795]:
model.score(X_train,y_train)

/usr/lib/python3.9/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(

0.9998290963909735

In [796]:
X

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1354,60.0,3,NaN,10316.0,1,2,0,3,0,4,...,0.0,0.0,3,4,4,0.0,6.0,2008.0,8,4
153,20.0,3,NaN,13500.0,1,2,3,3,0,4,...,0.0,0.0,3,4,4,0.0,3.0,2008.0,8,4
780,20.0,3,63.0,7875.0,1,2,3,3,0,4,...,0.0,0.0,3,4,4,0.0,6.0,2007.0,8,4
613,20.0,3,70.0,8402.0,1,2,3,3,0,4,...,0.0,0.0,3,4,4,0.0,12.0,2007.0,6,5
767,50.0,3,75.0,12508.0,1,2,0,3,0,4,...,0.0,0.0,3,4,2,1300.0,7.0,2008.0,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,20.0,3,NaN,15611.0,1,2,0,3,0,0,...,0.0,0.0,3,4,4,0.0,3.0,2008.0,8,0
146,30.0,4,51.0,6120.0,1,2,3,3,0,0,...,0.0,0.0,3,4,4,0.0,11.0,2009.0,8,4
1296,20.0,3,80.0,8700.0,1,2,3,3,0,4,...,0.0,0.0,3,2,4,0.0,12.0,2008.0,8,4
189,120.0,3,41.0,4923.0,1,2,3,3,0,4,...,224.0,0.0,3,4,4,0.0,8.0,2008.0,8,4
1147,70.0,3,75.0,12000.0,1,2,3,0,0,4,...,0.0,0.0,3,4,4,0.0,7.0,2009.0,8,4

In [797]:
for i in obj:
    X_test[i]= label_encoder.fit_transform(X_test[i])

In [798]:
model.score(X_test,y_test)

/usr/lib/python3.9/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(

0.7714389184917038

In [799]:
y_pred = model.predict(X_test)

/usr/lib/python3.9/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(

In [800]:
for i in obj:
    test[i]= label_encoder.fit_transform(test[i])

In [801]:
test = test.drop(columns=['Id'])

In [802]:


from sklearn.metrics import mean_squared_log_error
np.sqrt(mean_squared_log_error(y_test, y_pred))


# model.fit(X,y,verbose=False)
# model.score(X,y)



y_pred = model.predict(test)

sub = pd.DataFrame({'id':range(1461,1461+len(test)),'SalePrice':y_pred})
sub.to_csv('submission.csv',index=False)

/usr/lib/python3.9/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(

In [803]:
len(test)

1459

In [804]:
test

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,20,2,80.0,11622,1,2,3,3,0,4,...,120,0,2,2,3,0,6,2010,8,4
1,20,3,81.0,14267,1,2,0,3,0,0,...,0,0,2,4,0,12500,6,2010,8,4
2,60,3,74.0,13830,1,2,0,3,0,4,...,0,0,2,2,3,0,3,2010,8,4
3,60,3,78.0,9978,1,2,0,3,0,4,...,0,0,2,4,3,0,6,2010,8,4
4,120,3,43.0,5005,1,2,0,1,0,4,...,144,0,2,4,3,0,1,2010,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,4,21.0,1936,1,2,3,3,0,4,...,0,0,2,4,3,0,6,2006,8,4
1455,160,4,21.0,1894,1,2,3,3,0,4,...,0,0,2,4,3,0,4,2006,8,0
1456,20,3,160.0,20000,1,2,3,3,0,4,...,0,0,2,4,3,0,9,2006,8,0
1457,85,3,62.0,10441,1,2,3,3,0,4,...,0,0,2,2,2,700,7,2006,8,4
1458,60,3,74.0,9627,1,2,3,3,0,4,...,0,0,2,4,3,0,11,2006,8,4